# Azure Pipelines for GitHub :)
# More info: https://docs.microsoft.com/en-us/azure/devops/pipelines/?view=vsts
parameters:
  Name: 'WebAPI'
  RestoreBuildProjects: '**/*.API.csproj'
  BuildConfiguration: 'Release'
  WorkingDirectory: 'Src/Backend/Contoso.CognitivePipeline.API'

jobs:
- job: ${{ Parameters.Name }}
  pool:
    vmImage: 'ubuntu-16.04'
    demands: npm
  steps:
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: ${{ Parameters.RestoreBuildProjects }}

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: ${{ Parameters.RestoreBuildProjects }}
      arguments: '--configuration ${{ Parameters.BuildConfiguration }}'
      workingDirectory: ${{ Parameters.WorkingDirectory }}

  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      publishWebProjects: True
      arguments: '--configuration ${{ Parameters.BuildConfiguration }} --output $(build.artifactstagingdirectory)'
      zipAfterPublish: True
      workingDirectory: ${{ Parameters.WorkingDirectory }}

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
      ArtifactName: ContosoBackendAPIs