# Azure Pipelines for GitHub :)
# More info: https://docs.microsoft.com/en-us/azure/devops/pipelines/?view=vsts
trigger:
  branches:
    include:
      - master
      - azure-pipelines
  paths:
    include:
      - 'Src/FaceExplorer-App'
      - 'Src/Backend'

variables:
  buildConfiguration: 'Release'

jobs:
- template: azure-pipelines.webapi.yml
  parameters:
    name: ContosoBackendAPIs
#- template: azure-pipelines-function.yml
#  parameters:
#    name: ContosoBackendFunction
- template: azure-pipelines.angular.yml
  parameters:
    name: FaceExplorerApp