# Azure Pipelines for GitHub :)
# More info: https://docs.microsoft.com/en-us/azure/devops/pipelines/?view=vsts
trigger:
  branches:
    include:
      - master
      - azure-pipelines
  paths:
    include:
      - 'Src/FaceExplorer-App'
      - 'Src/Backend'
      - 'azure-pipelines.yml'

variables:
  buildConfiguration: 'Release'

jobs:
- template: azure-pipelines-webapp.yml
  parameters:
    Name: ContosoBackendAPIs
    RestoreBuildProjects: '**/*.API.csproj'
    BuildConfiguration: 'Release'
    WorkingDirectory: 'Src/Backend/Contoso.CognitivePipeline.API'
    ArtifactName: 'ContosoBackendAPIs'
    PublishWebApp: True

- template: azure-pipelines-function.yml
  parameters:
    Name: ContosoBackendFunction
    RestoreBuildProjects: '**/*.BackgroundServices.csproj'
    BuildConfiguration: 'Release'
    WorkingDirectory: 'Src/Backend/Contoso.CognitivePipeline.BackgroundServices'
    ArtifactName: 'ContosoBackendFunctions'
    PublishWebApp: False

- template: azure-pipelines-angular.yml
  parameters:
    Name: FaceExplorerApp